* How to get Openbox on Arch Linux for Junior Developers

#+BEGIN_QUOTE
Openbox is a highly configurable, next generation window manager with
extensive standards support.
#+END_QUOTE

Since /Openbox/ is just a window manager, you need to manually install
some other essential graphical applications, such as a terminal
emulator and a panel. And don't forget to install /Xorg/, because it
isn't pulled y default.

#+begin_src sh
sudo pacman -S xorg-server openbox obconf archlinux-xdg-menu tint2 nitrogen \
    gnome-backgrounds lxterminal pcmanfm conky lightdm lightdm-gtk-greeter
#+end_src

| =obconf=             | A GTK+ based configuration tool for the Openbox windowmanager |
| =archlinux-xdg-menu= | automatic generate WM menu from xdg files                     |
| =tint2=              | Basic, good-looking task manager for WMs                      |
| =nitrogen=           | Background browser and setter for X windows                   |
| =gnome-backgrounds=  | Background images and data for GNOME                          |
| =lxterminal=         | VTE-based terminal emulator (part of LXDE)                    |
| =pcmanfm=            | Extremely fast and lightweight file manager                   |
| =conky=              | Lightweight system monitor for X                              |

Copy the default /Openbox/ configuration files to the local user's
configuration folder:

#+begin_src sh
mkdir -p ~/.config/openbox
cp -a /etc/xdg/openbox/* ~/.config/openbox
#+end_src

We need =tint2=, =nitrogen= anc =conky= to start by default on our
session. For that, we need to add them to /Openbox/'s =autostart=
file:

#+begin_src sh
# ~/.config/openbox/autostart

tint2 &
nitrogen --reconfigure &
conky --daemonize &

# vim:ft=sh
#+end_src

Enable the =lightdm= service:

~sudo systemctl enable lightdm~

Start it:

~sudo systemctl start lightdm~

** xinit

To start an /Openbox/ session with /xinit/, the command is ~openbox-session~:

#+begin_src sh
# ~/.xinitrc

setxkbmap br # brazilian keyboard layout
openbox-session
#+end_src

** Openbox's right click menu

*** xdg-menu

*xdg-menu* is a tool that generates XDG Desktop Menus. We're going to
use /xdg_menu/ (from =archlinux-xdg-menu=) as a pipe menu, which:

#+begin_quote
...gives you the added benefit of having a menu that automatically
updates when you install new applications.
#+end_quote

For this, we just need a very simple /menu.xml/:

#+begin_src xml
<!-- ~/.config/openbox/menu.xml -->

<?xml version="1.0" encoding="UTF-8"?>
<openbox_menu xmlns="http://openbox.org/3.4/menu">
    <menu id="root-menu" label="Openbox 3">
        <menu id="applications" label="Applications" execute="~/bin/xdg_menu_maker" />
        <separator />
        <item label="Log Out">
            <action name="Exit">
                <prompt>yes</prompt>
            </action>
        </item>
    </menu>
</openbox_menu>
#+end_src

Note the command inside the /execute/ attribute:
/~/bin/xdg_menu_maker/. This is a custom script that we'll create and
looks like this:

#+begin_src sh
#!/bin/sh

# ~/bin/xdg_menu_maker

sed 's#<DefaultAppDirs/>#&<AppDir>'$HOME'/.local/share/applications</AppDir>#' \
	/etc/xdg/menus/arch-applications.menu > ~/.arch-menu.menu

xdg_menu --format openbox3-pipe --root-menu ~/.arch-menu.menu
#+end_src

After creating it, make executable: ~chmod +x ~/bin/xdg_menu_maker~.

The reason for this custom script is that we need to add an /AppDir/
directive instructing /xdg_menu/ to search
/~/.local/share/applications for Desktop Entries.

When all of this is done, right-click on your Desktop, navigate to
/System/, and click on /"Reconfigure Openbox"/.
