* How to get Openbox on Arch Linux for Junior Developers

#+BEGIN_QUOTE
Openbox is a highly configurable, next generation window manager with
extensive standards support.
#+END_QUOTE

Since /Openbox/ is just a window manager, you need to manually install
some other essential graphical applications, such as a terminal
emulator and a panel. And don't forget to install /Xorg/, because it
isn't pulled y default.

#+begin_src sh
sudo pacman -S xorg-server openbox obconf tint2 nitrogen gnome-backgrounds \
    alacritty pcmanfm lightdm lightdm-gtk-greeter
#+end_src

| =obconf=            | A GTK+ based configuration tool for the Openbox windowmanager |
| =tint2=             | Basic, good-looking task manager for WMs                      |
| =nitrogen=          | Background browser and setter for X windows                   |
| =gnome-backgrounds= | Background images and data for GNOME                          |
| =alacritty=         | A cross-platform, GPU-accelerated terminal emulator           |
| =pcmanfm=           | Extremely fast and lightweight file manager                   |

Copy the default /Openbox/ configuration files to the local user's
configuration folder:

#+begin_src sh
mkdir -p ~/.config/openbox
cp -a /etc/xdg/openbox/* ~/.config/openbox
#+end_src

We need =tint2= and =nitrogen= to start by default on our session. For
that, we need to add them to /Openbox/'s =autostart= file:

#+begin_src sh
# ~/.config/openbox/autostart

tint2 &
nitrogen --reconfigure

# vim:ft=sh
#+end_src

Enable the =lightdm= service:

~sudo systemctl enable lightdm~

Start it:

~sudo systemctl start lightdm~
