#+title: How to get OpenBSD up and running with i3wm

* The OpenBSD installer

** Keyboard layout

*** Brazilian

In the /Choose your keyboard layout/ prompt, type in =br= (Brazilian)
and hit /Enter/.

** Partitioning the disk

From the [[https://www.openbsd.org/faq/index.html][OpenBSD FAQ]]:

#+begin_quote
The term "partition" can mean two different things in *OpenBSD*:

- =disklabel(8)= partitions, also called filesystem partitions.
- =fdisk(8)= partitions, sometimes called /Master Boot Record/ (MBR) partitions.

All *OpenBSD* platforms use the =disklabel= program as the primary way to
manage filesystem partitions. On the platforms that use =fdisk=, one /MBR/
partition is used to hold all of the *OpenBSD* filesystems. This
partition can be sliced into 16 =disklabel= partitions, labeled =a=
through =p=. A few labels are special:

- =a=: The boot disk's a partition is your root partition.
- =b=: The boot disk's b partition is usually a swap partition.
- =c=: The c partition is always the entire disk.
#+end_quote

Firstly, in the /Use (W)hole disk MBR, whole disk (G)PT or (E)dit?/
prompt, allow the default option to be chosen (=whole=) by hitting
/Enter/. Then, in the /Use (A)uto layout, (E)dit auto layout, or
create (C)ustom layout?/, type in =c= and hit /Enter/.

We'll create a custom layout with the =disklabel= program, which is
running at this point.

To list all commands, use =?= or =h=. =p= prints the current partition
table.

At the end, it should look like this, with a 30G HDD and 2G of RAM:

| Label | Size | FS type | Mount point  |
|-------+------+---------+--------------|
| a:    | 1G   | 4.2BSD  | =/=          |
| b:    | 2G   | swap    | =[none]=     |
| c:    | 30G  | unused  |              |
| d:    | 1G   | 4.2BSD  | =/tmp=       |
| e:    | 2G   | 4.2BSD  | =/var=       |
| f:    | 3G   | 4.2BSD  | =/usr=       |
| g:    | 17G  | 4.2BSD  | =/usr/local= |
| h:    | 4G   | 4.2BSD  | =/home=      |

** xenodm

From a [[https://www.reddit.com/r/openbsd/comments/f40mq0/why_startx_does_not_work_for_nonroot_users][reddit post]]:

#+begin_quote
The =setuid= bit was removed from the *X* server for security reasons
which meant that =startx(1)= no longer works, it is recommended to use
=xenodm(1)= instead.
#+end_quote

In the /Do you want the X Window System to be started by xenodm(1)?/
prompt, type in =yes= and hit /Enter/.

** Let's install the sets!

In the /Directory does not contain SHA256.sig. Continue without
verification?/, type in =yes= and hit /Enter/.

From the [[https://www.openbsd.org/faq/index.html][OpenBSD FAQ]]:

#+begin_quote
The =installXX.iso= and =installXX.fs= images do not contain an =SHA256.sig=
file, so the installer will complain that it can't check the signature
of the included sets:

=Directory does not contain SHA256.sig. Continue without verification? [no]=

This is because it would make no sense for the installer to verify
them. If someone were to make a rogue installation image, they could
certainly change the installer to say the files were legitimate. If
the image's signature has been verified beforehand, it is safe to
answer "yes" at that prompt.
#+end_quote

* First steps

** syspatch

Log in as =root=. You'll land on an instance of =xterm= in the default
window manager: =fvwm=.

From the [[https://www.openbsd.org/faq/index.html][OpenBSD FAQ]]:

#+begin_quote
*Security Updates*

When a critical bug is found, the fix will be committed to the
*-current* tree (and made available in snapshot builds) as soon as
possible. From that point on, things are handled differently depending
on whether the problem was in the *OpenBSD* base system or a third party
package. ...

For the *OpenBSD* base system, security fixes are normally applied to
the two most recent releases. There are four options:
#+end_quote

The option referred to in this topic is applying binary patches with =syspatch=:

#+begin_quote
If you're running a supported release of *OpenBSD*, you can simply use
the =syspatch(8)= utility to upgrade any files in need of security or
reliability fixes. This is the quickest and easiest method to get the
base system up to date.
#+end_quote

On =xterm= run:

#+begin_src sh
syspatch
#+end_src

** Installing i3 and other third-party packages

Run:

#+begin_src sh
pkg_add vim bash i3 dmenu firefox
#+end_src

After the installation you'll be warned about the newly installed
font =terminus= and the /font path/.

** Setting up doas for the non-root user

=doas= allows you to run commands as another user, much like
=sudo=. But unlike it, =doas= has a much smaller feature set and is
part of the base system.

Create the file =/etc/doas.conf= with the following contents
(suppose the non-root username is =guilherme=):

#+begin_src sh
# /etc/doas.conf

permit guilherme as root
#+end_src

You may use freshly installed =vim= or the base system's =vi= for that
purpose.

** Changing the non-root user's default shell

On *OpenBSD*, the default shell is =ksh=. Change it to =bash= for
=guilherme=:

#+begin_src sh
chsh -s /usr/local/bin/bash guilherme
#+end_src

We're now ready to login as =guilherme=. Log out (as the =root= user)
by clicking on the desktop and selecting /Exit/ from the drop-down
menu.

* Setting up i3 as the non-root user

** i3status

Log in as =guilherme=. Likewise, you'll be faced with an instance of
=xterm= in the default window manager, which is =fvwm=. But your shell
is =bash= rather than =ksh=.

Copy the example =i3status= configuration to your home folder:

#+begin_src sh
cp /usr/local/share/examples/i3status/i3status.conf ~/.i3status.conf
#+end_src

** ~/.xsession

Create the file =~/.xsession=, which will act =xenodm='s =~/.xinitrc=:

#+begin_src sh
# ~/.xsession

xset +fp /usr/local/share/fonts/terminus

export LC_CTYPE="en_US.UTF-8"

xrandr -s 1600x900
i3

# vim: ft=sh
#+end_src

- The first command adds =terminus= to the font path.
- The second one sets the locale to /en_US.UTF-8/.
- The third sets the resolution (unsure whether it is necessary on
  non-virtualized environments).
- The fourth starts i3.

Available screen resolutions can be listed with =xrandr=.

Log out and log back in.

** i3 configuration file

As there still isn't an =i3= configuration file, it'll be created by
the =i3-config-wizard=, which is run automatically. Choose the default options.
